### ISSUE TITLE
Collaborate on the std::vector wrapper?

### ISSUE THREAD

**Issue by kaushalmodi** [Clonkk/nim-cppstl#3]
Hello,

I started wrapping the std::vector in Nim with doc strings and tests in https://github.com/kaushalmodi/std_vector. 

Would you like to merge the two libraries into yours? If so, I can send a PR that merges my comments and tests into your repo?

Ref: https://github.com/kaushalmodi/std_vector/issues/3

**Comment by Clonkk** [comment]
Hi @kaushalmodi,

This repository got transferred to me recently since I'll be in need to std::string.

Any PR that improves are welcome as I also think developing twice the same thing is not necessary.

**Comment by kaushalmodi** [comment]
@Clonkk Hello! Can you please review the PR's I opened in the process of closing this issue?

Thanks!

**Comment by Clonkk** [comment]
Sure ! 

I'll do this on Monday when I get back from my vacation 😁
